version: 2
jobs:
  build:
    docker:
      - image: tomasiser/docker-cinder:prebuilt
    steps:
      - checkout
      - run:
          name: Update git submodules (except lib/cinder)
          command: git submodule update --init --recursive ":(exclude)lib/cinder"
      - run:
          name: Prepare build (mkdir, cmake)
          command: |
            mkdir build
            cd build
            cmake .. -DPEPR3D_BUILD_CINDER=0 -DPEPR3D_CINDER_PATH="/dockercinder-prebuilt"
      - run:
          name: Run build (make)
          command: |
            cd build
            make
