version: 2
jobs:
  build:
    docker:
      - image: madduci/docker-linux-cpp
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: Checkout submodules
          command: |
            apt-get install -y git
            git submodule update --init --recursive
      - run:
          name: Install dependencies (apt-get)
          command: |
            apt-get update
            apt-get install -y libxcursor-dev \
              libxrandr-dev \
              libxinerama-dev \
              libxi-dev \
              libgl1-mesa-dev \
              libglu1-mesa-dev \
              zlib1g-dev \
              libfontconfig1-dev \
              libmpg123-dev \
              libsndfile1 \
              libsndfile1-dev \
              libpulse-dev \
              libasound2-dev \
              libcurl4-gnutls-dev \
              libgstreamer1.0-dev \
              libgstreamer-plugins-bad1.0-dev \
              libgstreamer-plugins-base1.0-dev \
              gstreamer1.0-libav \
              gstreamer1.0-alsa \
              gstreamer1.0-pulseaudio \
              gstreamer1.0-plugins-bad \
              libboost-all-dev
      - run:
          name: Prepare build (mkdir, cmake)
          command: |
            mkdir build
            cd build
            cmake .. -DCINDER_BOOST_USE_SYSTEM=1
      - run:
          name: Run build (make)
          command: |
            cd build
            make
